### PR TITLE
Fix possible asan

### PR DESCRIPTION
**Pull request by sundy-li**
May related to https://github.com/facebook/rocksdb/issues/7821

https://github.com/ClickHouse/ClickHouse/issues/18655

### CODE REVIEW

**Comment by sundy-li** [comment]
https://github.com/ClickHouse-Extras/rocksdb/blob/8b966f0ca298fc1475bd09d9775f32dff0fdce0a/env/fs_posix.cc#L768-L779

I think the `mutex_locked_files` released too early.  During [770-744), other thread may erase the `LockHoldingInfo& prev_info`  in `UnlockFile`

**Comment by sundy-li** [comment]
@nikitamikhaylov could you help review this?

**Review by alexey-milovidov — APPROVED** [review]
LGTM

**Comment by alexey-milovidov** [comment]
Thank you! Now we can update the submodule in ClickHouse repo, could you send a PR for that?

**Comment by sundy-li** [comment]
sure

**Pull request merged**
